name = "moe-counter-worker"
main = "dist/worker.js"
compatibility_date = "2026-05-14"
workers_dev = false

[build]
command = "npm run build"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_id = "08323087-a0a9-44cb-a940-c82df8945a47"
