import { DEFAULT_THEME, getTheme } from '../themes/index.js';

/**
 * @param {number|string} value
 * @param {number} min
 * @param {number} max
 * @returns {number}
 */
const clamp = (value, min, max) => Math.min(Math.max(value, min), max);

const toFiniteNumber = (value, fallback) => {
  const num = Number(value);
  return Number.isFinite(num) ? num : fallback;
};

const toFixed = (num, precision = 5) => parseFloat(Number(num).toFixed(precision));

/**
 * @param {object} params
 * @param {number|string} params.count 需要显示的数字
 * @param {string} params.theme 主题
 * @param {number|string} params.padding 数字总长度
 * @param {number|string} params.prefix 前缀数字, -1 表示不显示
 * @param {number|string} params.offset 数字间距
 * @param {'top'|'center'|'bottom'} params.align 垂直对齐方式
 * @param {number|string} params.scale 缩放比例
 * @param {'0'|'1'} params.pixelated 是否像素化
 * @param {'0'|'1'|'auto'} params.darkmode 深色模式亮度适配
 * @returns {string}
 */
const getCountImage = ({
  count,
  theme = DEFAULT_THEME,
  padding = 7,
  prefix = -1,
  offset = 0,
  align = 'top',
  scale = 1,
  pixelated = '1',
  darkmode = 'auto',
}) => {
  const themeData = getTheme(theme);
  const normalizedPadding = clamp(parseInt(toFiniteNumber(padding, 7), 10), 0, 16);
  const normalizedPrefix = clamp(parseInt(toFiniteNumber(prefix, -1), 10), -1, 999999);
  const normalizedOffset = clamp(toFiniteNumber(offset, 0), -500, 500);
  const normalizedScale = clamp(toFiniteNumber(scale, 1), 0.1, 2);
  const normalizedAlign = ['top', 'center', 'bottom'].includes(align) ? align : 'top';
  const normalizedPixelated = pixelated === '0' ? '0' : '1';
  const normalizedDarkmode = ['0', '1', 'auto'].includes(darkmode) ? darkmode : 'auto';

  const countArray = count.toString().padStart(normalizedPadding, '0').split('');

  if (normalizedPrefix >= 0) {
    countArray.unshift(...String(normalizedPrefix).split(''));
  }

  const { width, height, images } = themeData;
  const scaledWidth = width * normalizedScale;
  const scaledHeight = height * normalizedScale;

  let x = 0;
  const parts = countArray.reduce((pre, cur) => {
    const uri = images[cur];
    if (!uri) {
      return pre;
    }

    let yOffset = 0;
    if (normalizedAlign === 'center') {
      yOffset = (scaledHeight - scaledHeight) / 2;
    } else if (normalizedAlign === 'bottom') {
      yOffset = scaledHeight - scaledHeight;
    }

    const yAttribute = yOffset ? ` y="${toFixed(yOffset)}"` : '';
    const image = `<image x="${toFixed(x)}"${yAttribute} width="${toFixed(scaledWidth)}" height="${toFixed(scaledHeight)}" href="${uri}"/>`;
    x += scaledWidth + normalizedOffset;
    return pre + image;
  }, '');

  if (countArray.length > 0) {
    x -= normalizedOffset;
  }

  const style = [
    normalizedPixelated === '1' ? 'image-rendering: pixelated;' : '',
    normalizedDarkmode === '1' ? 'filter: brightness(.6);' : '',
  ]
    .filter(Boolean)
    .join(' ');
  const darkmodeStyle =
    normalizedDarkmode === 'auto' ? '@media (prefers-color-scheme: dark) { svg { filter: brightness(.6); } }' : '';

  return (
    '<?xml version="1.0" encoding="UTF-8"?>' +
    '<!-- Generated by https://github.com/journey-ad/Moe-Counter -->' +
    `<svg viewBox="0 0 ${toFixed(x)} ${toFixed(scaledHeight)}" width="${toFixed(x)}" height="${toFixed(scaledHeight)}" version="1.1"` +
    ' xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"' +
    `${style ? ` style="${style}"` : ''}>` +
    `<title>Moe Counter!</title><style>${darkmodeStyle}</style><g>${parts}</g></svg>`
  );
};

export { getCountImage };
